version: '3'

services:
  backend-blue:
    image: ${ECR_REGISTRY}/coursex-backend:latest
    container_name: coursex-backend-blue
    restart: always
    ports:
      - "8081:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./logs:/app/logs-blue

  backend-green:
    image: ${ECR_REGISTRY}/coursex-backend:latest
    container_name: coursex-backend-green
    restart: always
    ports:
      - "8082:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./logs:/app/logs-green