spring:
  config:
    activate:
      on-profile: test
    import:
      - classpath:jpa.yaml
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password:
    driver-class-name: ${DB_DRIVER_CLASS}