name: courseX main CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  detect_changes:
    runs-on: ubuntu-22.04
    outputs:
      backend_changed: ${{ steps.filter.outputs.backend }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check if backend changed
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            backend:
              - 'courseX-backend/**'

  build:
    needs: detect_changes
    if: needs.detect_changes.outputs.backend_changed == 'true'
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create resources folder and add env file
        run: |
          mkdir -p courseX-backend/src/main/resources/env
          echo "${{ secrets.ENV_FILE }}" > courseX-backend/src/main/resources/env/test.env

      - name: Build
        run: |
          cd courseX-backend
          chmod +x gradlew
          ./gradlew clean build
        shell: bash
