name: courseX main CD

on:
  push:
    branches: ['main']
    paths:
      - 'courseX-backend/**'
      - 'docker/**'

jobs:
  deploy_backend:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create resources folder and add env file
        run: |
          mkdir -p courseX-backend/src/main/resources/env
          echo "${{ secrets.PROD_ENV_FILE }}" > courseX-backend/src/main/resources/env/prod.env

      - name: Create test env file
        run: |
          mkdir -p courseX-backend/src/test/resources/env
          echo "ACTUATOR_PATH=/course-x-actuator" > courseX-backend/src/test/resources/env/test.env
          echo "DB_URL=jdbc:h2:mem:testdb" >> courseX-backend/src/test/resources/env/test.env
          echo "DB_USERNAME=sa" >> courseX-backend/src/test/resources/env/test.env
          echo "DB_PASSWORD=" >> courseX-backend/src/test/resources/env/test.env
          echo "DB_DRIVER_CLASS=org.h2.Driver" >> courseX-backend/src/test/resources/env/test.env
          echo "JPA_DATABASE_DIALECT=org.hibernate.dialect.H2Dialect" >> courseX-backend/src/test/resources/env/test.env
          echo "SPRING_PROFILES_ACTIVE=test" >> courseX-backend/src/test/resources/env/test.env

      - name: Build backend
        run: |
          cd courseX-backend
          chmod +x gradlew
          ./gradlew clean build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: coursex-backend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd courseX-backend
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Configure deployment files
        run: |
          export ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          export IMAGE_TAG=${{ github.sha }}
          export PREVIOUS_TAG=$(curl -s ${{ secrets.PREVIOUS_TAG_URL }} || echo "latest")
          envsubst < docker/docker-compose.yml > docker/docker-compose.processed.yml
          envsubst < docker/scripts/deploy.sh > docker/scripts/deploy.processed.sh

      - name: Copy deployment files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker/docker-compose.processed.yml,docker/scripts/deploy.processed.sh,docker/nginx/"
          target: "/home/${{ secrets.EC2_USER }}/coursex-deploy"
          strip_components: 1

      - name: Deploy to Backend EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}
            cd ~/coursex-deploy
            mv docker-compose.processed.yml docker-compose.yml
            mv deploy.processed.sh deploy.sh
            chmod +x deploy.sh
            echo "${{ secrets.PROD_ENV_FILE }}" > .env
            export ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
            export IMAGE_TAG=${{ github.sha }}
            ./deploy.sh
            echo "${{ github.sha }}" > ~/previous-tag.txt